FORMAT: 1A8
HOST: https://ahn.massivepointcloudproject.nl/api

# AHN pointcloud viewer web api

API used by the AHN pointcloud viewer.

The AHN uses the Amersfoort / RD New projection (EPSG:28992).

# Group Sizes

## Size of selection [/size/]

### Retrieve approximate number of points in selection [POST]

+ Request (application/json)

    + Attributes (object)
        + left: 124931.360 (number) - Most left or minimum x coordinate.
        + bottom: 484567.840 (number) - Most left or minimum y coordinate.
        + right: 126241.760 (number) - Most right or maximum x coordinate.
        + top: 485730.400 (number) - Most top or maximum y coordinate.
    
    + Body

            {
                "left": 124931.360,
                "bottom": 484567.840,
                "right": 126241.760,
                "top": 485730.400
            }

+ Response 200 (application/json)

    + Attributes (object)
        + points: 10193813 (number) - Approximate number of points in selection
        + level: 8 (number) - Level in octree pyramid to fetch points from. Lower number means less points.
        + coverage: 100 (number) - Percentage of points returned with given level.

    + Body

            {
                "points": 10193813,
                "level": 8,
                "coverage": 100
            }
            
+ Response 413 (text/html)

    When selection is too large.

    + Body

            Request Entity Too Large            

## Prepare laz file of selection [/laz]

### Submit job to create a laz file of selection [POST]

Background job will be started to create laz file of selection and send e-mail with url.

+ Request (application/json)

    + Attributes (object)
        + left: 124931.360 (number) - Most left or minimum x coordinate.
        + bottom: 484567.840 (number) - Most left or minimum y coordinate.
        + right: 126241.760 (number) - Most right or maximum x coordinate.
        + top: 485730.400 (number) - Most top or maximum y coordinate.
        + email: someone@example.com (string) - E-mail to send laz file url to.
        + level: 8 (number) - Level in octree pyramid to fetch points from. Lower number means less points.
    
    + Body
    
            {
                "left": 124931.360,
                "bottom": 484567.840,
                "right": 126241.760,
                "top": 485730.400,
                "email": "someone@example.com",
                "level": 8
            }


+ Response 200 (application/json)

    + Attributes (object)
        + points: 10193813 (number) - Approximate number of points in selection
        + level: 8 (number) - Level in octree pyramid to fetch points from. Lower number means less points.
        + coverage: 100 (number) - Percentage of points returned with given level.

    + Body

            {
                "points": 10193813,
                "level": 8,
                "coverage": 100
            }


+ Response 413 (text/html)
 
    When selection is too large.

    + Body

            Request Entity Too Large

