FORMAT: 1A
HOST: https://ahn.massivepointcloudproject.nl/api

# AHN pointcloud viewer web api

API used by the AHN pointcloud viewer.

The AHN uses the Amersfoort / RD New projection (EPSG:28992).

## Size of selection [/size/]

Parameters of request:

+ left: 124931.360 (required, number) ... Most left or minimum x coordinate.
+ bottom: 484567.840 (required, number) ... Most left or minimum y coordinate.
+ right: 126241.760 (required, number) ... Most right or maximum x coordinate.
+ top: 485730.400 (required, number) ... Most top or maximum y coordinate.

### Retrieve approximate number of points in selection [POST]

+ Request (application/json)

        {
            "left": 124931.360,
            "bottom": 484567.840,
            "right": 126241.760,
            "top": 485730.400
        }

+ Response 200 (application/json)

        {
            "points": 10193813
        }

## Prepare laz file of selection [/laz]

Parameters of request:

+ left: 124931.360 (required, number) ... Most left or minimum x coordinate.
+ bottom: 484567.840 (required, number) ... Most left or minimum y coordinate.
+ right: 126241.760 (required, number) ... Most right or maximum x coordinate.
+ top: 485730.400 (required, number) ... Most top or maximum y coordinate.
+ email (string) - E-mail to send laz file url to.

### Submit job to create a laz file of selection [POST]

Background job will be started to create laz file of selection and send e-mail with url.

+ Request (application/json)

        {
            "left": 124931.360,
            "bottom": 484567.840,
            "right": 126241.760,
            "top": 485730.400,
            "email": "someone@example.com"
        }


+ Response 200 (application/json)

        When selection is ok.

        + Body 
        
            {
                "points": 10193813
            }

+ Response 413 (text/html)

        When selection is too big.

        + Body

            Request Entity Too Large

